# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'NovelConverter_layout.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_NovelConverter(object):
    def setupUi(self, NovelConverter):
        NovelConverter.setObjectName("NovelConverter")
        NovelConverter.resize(1478, 746)
        self.label = QtWidgets.QLabel(NovelConverter)
        self.label.setGeometry(QtCore.QRect(10, 10, 56, 12))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(NovelConverter)
        self.label_2.setGeometry(QtCore.QRect(500, 10, 56, 12))
        self.label_2.setObjectName("label_2")
        self.layoutWidget = QtWidgets.QWidget(NovelConverter)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 30, 971, 681))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.inputPlace = QtWidgets.QTextEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.inputPlace.setFont(font)
        self.inputPlace.setObjectName("inputPlace")
        self.horizontalLayout.addWidget(self.inputPlace)
        self.outputPlace = QtWidgets.QTextEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.outputPlace.setFont(font)
        self.outputPlace.setObjectName("outputPlace")
        self.horizontalLayout.addWidget(self.outputPlace)
        self.pushButton = QtWidgets.QPushButton(NovelConverter)
        self.pushButton.setGeometry(QtCore.QRect(1337, 712, 131, 30))
        self.pushButton.setObjectName("pushButton")
        self.importButton = QtWidgets.QPushButton(NovelConverter)
        self.importButton.setGeometry(QtCore.QRect(10, 717, 75, 23))
        self.importButton.setObjectName("importButton")
        self.exportButton = QtWidgets.QPushButton(NovelConverter)
        self.exportButton.setGeometry(QtCore.QRect(90, 717, 75, 23))
        self.exportButton.setObjectName("exportButton")
        self.kakuyomuPlace = QtWidgets.QTextEdit(NovelConverter)
        self.kakuyomuPlace.setGeometry(QtCore.QRect(986, 30, 481, 679))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.kakuyomuPlace.setFont(font)
        self.kakuyomuPlace.setObjectName("kakuyomuPlace")
        self.label_3 = QtWidgets.QLabel(NovelConverter)
        self.label_3.setGeometry(QtCore.QRect(987, 8, 71, 16))
        self.label_3.setObjectName("label_3")

        self.retranslateUi(NovelConverter)
        QtCore.QMetaObject.connectSlotsByName(NovelConverter)

    def retranslateUi(self, NovelConverter):
        _translate = QtCore.QCoreApplication.translate
        NovelConverter.setWindowTitle(_translate("NovelConverter", "Novel Converter"))
        self.label.setText(_translate("NovelConverter", "Before"))
        self.label_2.setText(_translate("NovelConverter", "After"))
        self.pushButton.setText(_translate("NovelConverter", "Go to restore mode"))
        self.importButton.setText(_translate("NovelConverter", "File import"))
        self.exportButton.setText(_translate("NovelConverter", "File export"))
        self.label_3.setText(_translate("NovelConverter", "Kakuyomu"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    NovelConverter = QtWidgets.QDialog()
    ui = Ui_NovelConverter()
    ui.setupUi(NovelConverter)
    NovelConverter.show()
    sys.exit(app.exec_())
